export const authenticateUser = () => {
    try {
        
    } catch (error) {
        console.error('error' , error)
        throw new Error('error authenticating the user')
    }
}